# Generated by Django 5.2.7 on 2025-12-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_cartitem_unique_together_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telefono_envio',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
