# Generated by Django 5.2.7 on 2025-12-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_order_telefono_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telefono_envio',
            field=models.CharField(max_length=20),
        ),
    ]
